server:
  port:  8270

eureka:
#  instance:
#    hostname: hello-service
#    prefer-ip-address: true
#    ip-address: ${eureka.instance.hostname} #只有当prefer-ip-address: true 时才生效
#    instance-id: ${eureka.instance.hostname}:${server.port}  # 将Instance ID设置成IP:端口的形式
  client:
    service-url:
      defaultZone: http://eurekaServer:8280/eureka
spring:
  application:
    name: hello-service


