spring:
  profiles: peer2

server:
  port: 8282

eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone:  http://peer1:8281/eureka/,http://peer2:8282/eureka/,http://peer3:8283/eureka/

